version: "3"

services:
  app:
    build: .
    volumes:
      - .:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./.docker/openssl/openssl.cnf:/etc/ssl/openssl.cnf
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.15.0-alpine
    volumes: 
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    restart: always
    tty: true
    ports:
      - "8020:80"
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    ports:
      - "33010:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8021:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100M
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PORT=3306
      - PMA_PASSWORD=root

  redis:
    image: redis:alpine